__version__ = '0.1.0'
# __status__ = 'Development Status :: 5 - Production/Stable'
# __status__ = 'Development Status :: 4 - Beta'
__status__ = 'Development Status :: 3 - Alpha'
# __status__ = 'Development Status :: 2 - Pre-Alpha'
